In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [3]:
df= pd.read_csv('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [4]:
df = pd.read_csv('data.csv
                 ')

SyntaxError: EOL while scanning string literal (<ipython-input-4-0839e80b4fd4>, line 1)

In [5]:
df = pd.read_csv('data.csv')


In [6]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   98.332734         0   36          1          -1              0
1  101.488868         1   88          0           0              1
2   98.295029         1   71          1          -1              1
3   99.440096         1   80          0           1              0
4   98.917922         1    6          1           1              0

In [7]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2570  100.426833         1   58          1           0              1
2571   99.970904         1   63          0           0              0
2572   98.072294         0   38          1          -1              1
2573   98.503010         1   55          0           1              1
2574   98.689390         0   83          0           0              1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2575 entries, 0 to 2574
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2575 non-null   float64
 1   bodyPain       2575 non-null   int64  
 2   age            2575 non-null   int64  
 3   runnyNose      2575 non-null   int64  
 4   diffBreath     2575 non-null   int64  
 5   infectionProb  2575 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 120.8 KB


In [9]:
df['diffBreath'].value_counts()

 0    885
-1    853
 1    837
Name: diffBreath, dtype: int64

In [10]:
df['runnyNose'].value_counts()

0    1310
1    1265
Name: runnyNose, dtype: int64

In [11]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2575.000000  2575.000000  2575.000000  2575.000000  2575.000000   
mean    100.022494     0.493981    50.023301     0.491262    -0.006214   
std       1.169163     0.500061    28.635022     0.500021     0.810264   
min      98.000537     0.000000     1.000000     0.000000    -1.000000   
25%      98.979986     0.000000    26.000000     0.000000    -1.000000   
50%     100.031807     0.000000    50.000000     0.000000     0.000000   
75%     101.045854     1.000000    75.000000     1.000000     1.000000   
max     101.997330     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2575.000000  
mean        0.514175  
std         0.499896  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

In [12]:
import numpy as np

In [13]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [14]:
np.random.permutation(7)

array([3, 1, 2, 6, 0, 4, 5])

In [15]:
train, test = data_split(df, 0.2)

In [16]:
train


fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1703  100.388567         0   41          1           0              0
1675  101.336653         1   20          0          -1              0
1518   99.928020         1   45          1          -1              0
361    98.443597         0    1          1          -1              1
1544  100.205567         0   21          0           0              1
...          ...       ...  ...        ...         ...            ...
1638   98.512446         0   85          1           1              0
1095  101.781375         0    2          0          -1              1
1130   98.246650         1   14          1           0              1
1294   99.822245         1   63          1           0              1
860   101.343275         0    9          1           1              1

[2060 rows x 6 columns]

In [17]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1644   99.902364         1   26          1           0              0
1189   98.936990         0    9          0          -1              1
495    98.746561         1   62          1           0              1
1656  100.807170         0   24          1           1              1
651   101.080045         0   80          0           0              0
...          ...       ...  ...        ...         ...            ...
1627  100.723407         1   62          1          -1              1
471    99.101795         1   53          0           0              1
700    98.900111         0   79          0           0              0
25     99.767231         1   98          0           0              1
755    99.305254         0   10          1          -1              0

[515 rows x 6 columns]

In [18]:
len(data)

NameError: name 'data' is not defined

In [19]:
len(df)

2575

In [20]:
x.train = train[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

NameError: name 'x' is not defined

In [21]:
x_train = train[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [22]:
y_train = train[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [26]:
y_train = train[['infectionProb']].to_numpy().reshape(2060,)

In [27]:
y_train


array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [28]:
x_test = test[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [29]:
y_test = test[['infectionProb']].to_numpy().reshape(515,)

In [30]:
y_test

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,

In [31]:
x_test

array([[99.90236415,  1.        , 26.        ,  1.        ,  0.        ],
       [98.93698985,  0.        ,  9.        ,  0.        , -1.        ],
       [98.74656082,  1.        , 62.        ,  1.        ,  0.        ],
       ...,
       [98.90011052,  0.        , 79.        ,  0.        ,  0.        ],
       [99.76723146,  1.        , 98.        ,  0.        ,  0.        ],
       [99.30525419,  0.        , 10.        ,  1.        , -1.        ]])

In [32]:
x_train

array([[100.388567  ,   0.        ,  41.        ,   1.        ,
          0.        ],
       [101.3366533 ,   1.        ,  20.        ,   0.        ,
         -1.        ],
       [ 99.92801977,   1.        ,  45.        ,   1.        ,
         -1.        ],
       ...,
       [ 98.24665037,   1.        ,  14.        ,   1.        ,
          0.        ],
       [ 99.82224468,   1.        ,  63.        ,   1.        ,
          0.        ],
       [101.3432751 ,   0.        ,   9.        ,   1.        ,
          1.        ]])

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
  clf = LogisticRegression()
    

In [35]:
 clf.fit(X_train, Y_train)

NameError: name 'X_train' is not defined

In [36]:
clf.fit(x_train, y_train)

LogisticRegression()

In [37]:
inputFeatures = [102, 1,22, -1, 1]

In [38]:
infProb = clf.predict_proba([inputFeatures])[0][1]

In [39]:
infProb

0.5415464146319815